// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgbLpZUP7UTNr2K5pLtiuefc1sXD_1N4c',
    appId: '1:209652002579:web:69163ee839f6d886f834e6',
    messagingSenderId: '209652002579',
    projectId: 'prioro-1b8e6',
    authDomain: 'prioro-1b8e6.firebaseapp.com',
    storageBucket: 'prioro-1b8e6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9u0cPkyzHGRSw43nQJAqQuApzpfQBW2A',
    appId: '1:209652002579:android:11c761e7ccf34dfdf834e6',
    messagingSenderId: '209652002579',
    projectId: 'prioro-1b8e6',
    storageBucket: 'prioro-1b8e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-RWbVSn6tK7bhC7fuhfxlz__EnDc-KGc',
    appId: '1:209652002579:ios:5e1262a81b4c39a1f834e6',
    messagingSenderId: '209652002579',
    projectId: 'prioro-1b8e6',
    storageBucket: 'prioro-1b8e6.firebasestorage.app',
    iosBundleId: 'com.example.prioro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-RWbVSn6tK7bhC7fuhfxlz__EnDc-KGc',
    appId: '1:209652002579:ios:5e1262a81b4c39a1f834e6',
    messagingSenderId: '209652002579',
    projectId: 'prioro-1b8e6',
    storageBucket: 'prioro-1b8e6.firebasestorage.app',
    iosBundleId: 'com.example.prioro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgbLpZUP7UTNr2K5pLtiuefc1sXD_1N4c',
    appId: '1:209652002579:web:521d796874ecab6af834e6',
    messagingSenderId: '209652002579',
    projectId: 'prioro-1b8e6',
    authDomain: 'prioro-1b8e6.firebaseapp.com',
    storageBucket: 'prioro-1b8e6.firebasestorage.app',
  );
}
